using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PFOH.Api.Data;
using PFOH.Api.Dtos;
using PFOH.Api.Models;

namespace PFOH.Api.Controllers;

[ApiController]
[Route("api/honorees")]
[AllowAnonymous]
public class HonoreesController(PfohDbContext db) : ControllerBase
{
    private static readonly HttpClient Http = new();

    [HttpGet("search")]
    public async Task<ActionResult<IReadOnlyList<HonoreeSearchResultDto>>> Search(
        [FromQuery] string? q,
        [FromQuery] int take = 25,
        CancellationToken ct = default)
    {
        take = Math.Clamp(take, 1, 50);

        var query = db.HonoreeSearchResults
            .AsNoTracking()
            .Where(h => h.IsActive);

        if (!string.IsNullOrWhiteSpace(q))
        {
            var term = q.Trim();
            var pattern = $"%{term}%";

            query = query.Where(h =>
                EF.Functions.Like(h.FullName, pattern) ||
                EF.Functions.Like(h.FirstName, pattern) ||
                EF.Functions.Like(h.LastName, pattern) ||
                (h.Nickname != null && EF.Functions.Like(h.Nickname, pattern)) ||
                EF.Functions.Like(h.Rank, pattern) ||
                (h.ServiceBranchName != null && EF.Functions.Like(h.ServiceBranchName, pattern)) ||
                (h.FlagGrid != null && EF.Functions.Like(h.FlagGrid, pattern)) ||
                (h.SponsorName != null && EF.Functions.Like(h.SponsorName, pattern)));
        }

        var results = await query
            .OrderBy(h => h.LastName)
            .ThenBy(h => h.FirstName)
            .Take(take)
            .Select(h => new HonoreeSearchResultDto(
                h.Id,
                h.FullName,
                h.FirstName,
                h.MiddleName,
                h.LastName,
                h.Suffix,
                h.Nickname,
                h.Rank,
                h.KIA,
                h.ServiceBranchName,
                h.FlagGrid,
                h.SponsorName,
                h.ImageUrl,
                h.PDFUrl,
                h.IsActive))
            .ToListAsync(ct);

        return Ok(results);
    }

    [HttpGet("{honoreeId:int}/pdf")]
    public async Task<IActionResult> OpenOrCreatePdf(int honoreeId, CancellationToken ct)
    {
        var honoree = await db.HonoreeSearchResults
            .AsNoTracking()
            .FirstOrDefaultAsync(h => h.Id == honoreeId && h.IsActive, ct);

        if (honoree is null)
        {
            return NotFound("Honoree was not found.");
        }

        if (!string.IsNullOrWhiteSpace(honoree.PDFUrl) &&
            await ExistingPdfIsAvailableAsync(honoree.PDFUrl, ct))
        {
            return Redirect(honoree.PDFUrl);
        }

        var pdf = CreateGeneratedHonoreePdf(honoree);
        var fileName = SanitizeFileName($"{honoree.FullName}-honoree.pdf");

        Response.Headers["Content-Disposition"] = $"inline; filename=\"{fileName}\"";
        Response.Headers["X-PFOH-PDF-Source"] = "generated";

        return File(pdf, "application/pdf");
    }

    private async Task<bool> ExistingPdfIsAvailableAsync(string pdfUrl, CancellationToken ct)
    {
        if (!TryBuildAbsoluteUri(pdfUrl, out var uri))
        {
            return false;
        }

        try
        {
            using var request = new HttpRequestMessage(HttpMethod.Get, uri);
            using var response = await Http.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);

            return response.IsSuccessStatusCode;
        }
        catch
        {
            return false;
        }
    }

    private bool TryBuildAbsoluteUri(string url, out Uri uri)
    {
        if (Uri.TryCreate(url, UriKind.Absolute, out uri!))
        {
            return true;
        }

        var relativeUrl = url.StartsWith('/') ? url : $"/{url}";
        return Uri.TryCreate($"{Request.Scheme}://{Request.Host}{relativeUrl}", UriKind.Absolute, out uri!);
    }

    private static byte[] CreateGeneratedHonoreePdf(HonoreeSearchResult honoree)
    {
        var lines = new List<(string Text, int FontSize, bool Bold)>
        {
            ("Plano Flags of Honor", 18, true),
            ("Generated Honoree Record", 12, false),
            ("", 10, false),
            (honoree.FullName, 20, true),
            (JoinNonEmpty(" • ", honoree.Rank, honoree.ServiceBranchName), 12, false),
            ($"Flag grid: {ValueOrDash(honoree.FlagGrid)}", 12, false),
            ($"Submitter: {ValueOrDash(honoree.SponsorName)}", 12, false)
        };

        if (honoree.KIA)
        {
            lines.Add(("Killed in action / Gold Star recognition", 12, true));
        }

        AddSection(lines, "Awards", honoree.Awards);
        AddSection(lines, "Tribute", null);

        lines.Add(("", 10, false));
        lines.Add(("This PDF was generated by Plano Flags of Honor because the original honoree PDF was unavailable.", 9, false));
        lines.Add(("Please verify all information before using this generated document for printing or publication.", 9, false));

        var content = BuildPdfTextContent(lines);
        return BuildSimplePdf(content);
    }

    private static void AddSection(List<(string Text, int FontSize, bool Bold)> lines, string title, string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return;
        }

        lines.Add(("", 10, false));
        lines.Add((title, 13, true));

        foreach (var line in Wrap(value.Trim(), 82))
        {
            lines.Add((line, 10, false));
        }
    }

    private static string BuildPdfTextContent(List<(string Text, int FontSize, bool Bold)> lines)
    {
        var sb = new StringBuilder();
        var y = 742;

        sb.AppendLine("BT");

        foreach (var line in lines)
        {
            if (y < 72)
            {
                break;
            }

            if (string.IsNullOrWhiteSpace(line.Text))
            {
                y -= 14;
                continue;
            }

            var fontName = line.Bold ? "F2" : "F1";
            sb.AppendLine($"/{fontName} {line.FontSize} Tf");
            sb.AppendLine($"1 0 0 1 72 {y} Tm");
            sb.AppendLine($"({EscapePdfText(line.Text)}) Tj");

            y -= Math.Max(line.FontSize + 7, 14);
        }

        sb.AppendLine("ET");
        return sb.ToString();
    }

    private static byte[] BuildSimplePdf(string content)
    {
        var output = new List<byte>();
        var offsets = new List<int>();

        void Write(string value) => output.AddRange(Encoding.ASCII.GetBytes(value));

        void WriteObject(int objectNumber, string body)
        {
            offsets.Add(output.Count);
            Write($"{objectNumber} 0 obj\n");
            Write(body);
            Write("\nendobj\n");
        }

        var contentBytes = Encoding.ASCII.GetBytes(content);

        Write("%PDF-1.4\n");
        WriteObject(1, "<< /Type /Catalog /Pages 2 0 R >>");
        WriteObject(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
        WriteObject(3, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>");
        WriteObject(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
        WriteObject(5, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
        WriteObject(6, $"<< /Length {contentBytes.Length} >>\nstream\n{content}endstream");

        var xrefOffset = output.Count;
        Write("xref\n");
        Write("0 7\n");
        Write("0000000000 65535 f \n");

        foreach (var offset in offsets)
        {
            Write($"{offset:D10} 00000 n \n");
        }

        Write("trailer\n");
        Write("<< /Size 7 /Root 1 0 R >>\n");
        Write("startxref\n");
        Write($"{xrefOffset}\n");
        Write("%%EOF\n");

        return output.ToArray();
    }

    private static string EscapePdfText(string value)
    {
        var ascii = new string(value.Select(ch => ch is >= ' ' and <= '~' ? ch : '?').ToArray());
        return ascii.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
    }

    private static IEnumerable<string> Wrap(string value, int maxLength)
    {
        var words = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var current = new StringBuilder();

        foreach (var word in words)
        {
            if (current.Length + word.Length + 1 > maxLength)
            {
                if (current.Length > 0)
                {
                    yield return current.ToString();
                    current.Clear();
                }
            }

            if (current.Length > 0)
            {
                current.Append(' ');
            }

            current.Append(word);
        }

        if (current.Length > 0)
        {
            yield return current.ToString();
        }
    }

    private static string JoinNonEmpty(string separator, params string?[] values)
    {
        return string.Join(separator, values.Where(v => !string.IsNullOrWhiteSpace(v)));
    }

    private static string ValueOrDash(string? value) => string.IsNullOrWhiteSpace(value) ? "-" : value;

    private static string SanitizeFileName(string value)
    {
        var invalid = Path.GetInvalidFileNameChars().ToHashSet();
        var sanitized = new string(value.Select(ch => invalid.Contains(ch) ? '-' : ch).ToArray());
        return string.IsNullOrWhiteSpace(sanitized) ? "honoree.pdf" : sanitized;
    }
}
